# Generated by Django 5.2.16 on 2026-07-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forum_handle",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
