# Generated by Django 5.2.17 on 2026-09-23 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tools", "0002_comment_commentlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, help_text="Markdown")),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="カンマ区切り", max_length=200
                    ),
                ),
                (
                    "work_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="業務カテゴリ id の配列（ツールと同じ軸）",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "募集中"),
                            ("adopted", "テーマ化済み"),
                            ("declined", "見送り"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "アイデア",
                "verbose_name_plural": "アイデア",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdeaComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="themes.idea",
                    ),
                ),
            ],
            options={
                "verbose_name": "アイデアへのコメント",
                "verbose_name_plural": "アイデアへのコメント",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.CharField(help_text="一覧に出る一行説明", max_length=280),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="背景・目的・進め方（Markdown）"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recruiting", "仲間募集中"),
                            ("active", "着手中"),
                            ("frozen", "凍結"),
                            ("done", "完了"),
                            ("merged", "統合済み"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="カンマ区切り", max_length=200
                    ),
                ),
                (
                    "work_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="業務カテゴリ id の配列（ツールと同じ軸）",
                    ),
                ),
                (
                    "freeze_reason",
                    models.TextField(
                        blank=True,
                        help_text="凍結理由。何が課題で止めたのかを知見として残す",
                    ),
                ),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("last_progress_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_from",
                        to="themes.theme",
                    ),
                ),
                (
                    "origin_idea",
                    models.ForeignKey(
                        blank=True,
                        help_text="このテーマの元になったアイデア",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_themes",
                        to="themes.idea",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_themes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resulting_tool",
                    models.ForeignKey(
                        blank=True,
                        help_text="このテーマから生まれたツール",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_themes",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "テーマ",
                "verbose_name_plural": "テーマ",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="idea",
            name="promoted_theme",
            field=models.OneToOneField(
                blank=True,
                help_text="昇格先のテーマ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="_promoted_from",
                to="themes.theme",
            ),
        ),
        migrations.CreateModel(
            name="ThemeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("progress", "進捗"),
                            ("comment", "コメント"),
                            ("system", "記録"),
                        ],
                        default="progress",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField(help_text="Markdown")),
                ("progress_percent", models.IntegerField(blank=True, null=True)),
                ("status_at_post", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="システム記録の場合は null",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="themes.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "テーマの記録",
                "verbose_name_plural": "テーマの記録",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThemeJoinRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="やりたいこと・できることなど"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "承認待ち"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_theme_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="themes.theme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "参加申請",
                "verbose_name_plural": "参加申請",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThemeMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "発起人"), ("member", "メンバー")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="themes.theme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "テーマメンバー",
                "verbose_name_plural": "テーマメンバー",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="IdeaVote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="themes.idea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "アイデアへの賛同",
                "verbose_name_plural": "アイデアへの賛同",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("idea", "user"), name="uniq_idea_vote_per_user"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(fields=["status"], name="themes_them_status_cafcda_idx"),
        ),
        migrations.AddIndex(
            model_name="theme",
            index=models.Index(
                fields=["-updated_at"], name="themes_them_updated_d1eed6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="themejoinrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("theme", "user"),
                name="uniq_pending_join_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="thememember",
            constraint=models.UniqueConstraint(
                fields=("theme", "user"), name="uniq_theme_member"
            ),
        ),
    ]
