# Generated by Django 5.2.15 on 2026-06-19 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("impression", "表示（一覧露出）"),
                            ("view", "詳細閲覧"),
                            ("readme_scroll", "README閲覧"),
                            ("download", "ダウンロード/アクセス"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=64)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="tools.tool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "アクティビティログ",
                "verbose_name_plural": "アクティビティログ",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tool", "action"], name="metrics_act_tool_id_b3d98d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="metrics_act_created_a62e1a_idx"
                    ),
                ],
            },
        ),
    ]
