# Generated by Django 5.2.17 on 2026-09-23 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event", models.CharField(db_index=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "送信成功"),
                            ("failed", "送信失敗"),
                            ("skipped", "送信せず"),
                        ],
                        max_length=10,
                    ),
                ),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Webhook送信ログ",
                "verbose_name_plural": "Webhook送信ログ",
                "ordering": ["-created_at"],
            },
        ),
    ]
