# Generated by Django 5.2.15 on 2026-06-19 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AspiceProcess",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SYS", "システム"),
                            ("SWE", "ソフトウェア"),
                            ("SUP", "支援"),
                            ("MAN", "管理"),
                            ("ACQ", "取得"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "v_model_position",
                    models.CharField(
                        choices=[
                            ("left", "左辺（要件・設計）"),
                            ("bottom", "底辺（実装）"),
                            ("right", "右辺（検証・テスト）"),
                            ("support", "支援プロセス"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "A-SPICEプロセス",
                "verbose_name_plural": "A-SPICEプロセス",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=280)),
                ("readme", models.TextField(blank=True)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("copilot_agent", "Copilotエージェント"),
                            ("notebook_lm", "NotebookLM"),
                            ("github_repo", "GitHubリポジトリ"),
                            ("zip_upload", "ZIPアップロード"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("access_url", models.URLField(blank=True, null=True)),
                (
                    "zip_file",
                    models.FileField(blank=True, null=True, upload_to="tool_zips/"),
                ),
                ("tags", models.CharField(blank=True, max_length=500)),
                (
                    "work_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="作業カテゴリのタグ一覧 (例: meeting, mail, document)",
                    ),
                ),
                ("effect_qualitative", models.TextField(blank=True)),
                (
                    "effect_hours_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forked_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "ツール",
                "verbose_name_plural": "ツール",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="screenshots/")),
                ("display_order", models.IntegerField(default=0)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "スクリーンショット",
                "verbose_name_plural": "スクリーンショット",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "承認待ち"),
                            ("granted", "承認"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "アクセス申請",
                "verbose_name_plural": "アクセス申請",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolAspiceProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.aspiceprocess",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.tool"
                    ),
                ),
            ],
            options={
                "verbose_name": "ツール-A-SPICE紐付け",
                "verbose_name_plural": "ツール-A-SPICE紐付け",
                "unique_together": {("tool", "process")},
            },
        ),
        migrations.AddField(
            model_name="tool",
            name="aspice_processes",
            field=models.ManyToManyField(
                blank=True,
                related_name="tools",
                through="tools.ToolAspiceProcess",
                to="tools.aspiceprocess",
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "いいね",
                "verbose_name_plural": "いいね",
                "unique_together": {("user", "tool")},
            },
        ),
    ]
