# Generated by Django 5.2.16 on 2026-07-30 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(blank=True, help_text="1レス目の本文（Markdown）"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("idea", "💡 ほしいツール"),
                            ("discussion", "🗣️ 相談・議論"),
                            ("share", "📣 事例共有"),
                            ("other", "💬 雑談"),
                        ],
                        default="idea",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="カンマ区切り", max_length=200
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, help_text="上部に固定"),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, help_text="レス受付を停止"),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("last_posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "フォーラムスレッド",
                "verbose_name_plural": "フォーラムスレッド",
                "ordering": ["-is_pinned", "-last_posted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.IntegerField(help_text="スレッド内のレス番号（>>N の N）"),
                ),
                ("body", models.TextField(help_text="Markdown。>>N でレス参照")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="forum.forumthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "フォーラムレス",
                "verbose_name_plural": "フォーラムレス",
                "ordering": ["number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("thread", "number"), name="uniq_thread_post_number"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ThreadVote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="forum.forumthread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "スレッド投票",
                "verbose_name_plural": "スレッド投票",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("thread", "user"), name="uniq_thread_vote_user"
                    )
                ],
            },
        ),
    ]
