# Generated by Django 5.2.16 on 2026-07-30 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumAnonName",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "label",
                    models.CharField(
                        help_text="例: 名無しの開発者", max_length=50, unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="外すと選ばれなくなる"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="小さい順に並ぶ（表示用）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "名無し表記",
                "verbose_name_plural": "名無し表記",
                "ordering": ["order", "label"],
            },
        ),
        migrations.AddField(
            model_name="forumpost",
            name="poster_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="forumthread",
            name="poster_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="ForumRevealLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("thread", "スレッド"), ("post", "レス")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "reason",
                    models.CharField(
                        blank=True, help_text="特定理由（任意）", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        help_text="特定操作を行った管理者",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_reveals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revealed_user",
                    models.ForeignKey(
                        help_text="特定された投稿者",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forum_revealed_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "投稿者特定ログ",
                "verbose_name_plural": "投稿者特定ログ",
                "ordering": ["-created_at"],
            },
        ),
    ]
