# Generated by Django 5.2.16 on 2026-07-21 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="docs/attachments/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doc_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ドキュメント添付画像",
                "verbose_name_plural": "ドキュメント添付画像",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("guide", "ガイド"), ("qa", "Q&A")], max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="絵文字 1〜2 字", max_length=10
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="docs.doccategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "ドキュメントカテゴリ",
                "verbose_name_plural": "ドキュメントカテゴリ",
                "ordering": ["kind", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GuideArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("body", models.TextField(blank=True, help_text="Markdown")),
                ("order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guide_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"kind": "guide"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guide_articles",
                        to="docs.doccategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "ガイド記事",
                "verbose_name_plural": "ガイド記事",
                "ordering": ["category__order", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, help_text="Markdown")),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="カンマ区切り", max_length=200
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, help_text="良い回答が付いたら管理者がチェック"
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_asked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kind": "qa"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="docs.doccategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "質問",
                "verbose_name_plural": "質問",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(help_text="Markdown")),
                (
                    "is_accepted",
                    models.BooleanField(default=False, help_text="ベストアンサー印"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="docs.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "回答",
                "verbose_name_plural": "回答",
                "ordering": ["-is_accepted", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="doccategory",
            constraint=models.UniqueConstraint(
                fields=("kind", "slug"), name="uniq_kind_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="guidearticle",
            constraint=models.UniqueConstraint(
                fields=("category", "slug"), name="uniq_guide_category_slug"
            ),
        ),
    ]
