# Generated by Django 5.2.17 on 2026-08-27 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forum", "0002_forumanonname_forumpost_poster_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link", models.URLField(max_length=1000, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("title_ja", models.CharField(blank=True, max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, db_index=True, max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "published",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, max_length=1000)),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "discussion_thread",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_article",
                        to="forum.forumthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "ニュース記事",
                "verbose_name_plural": "ニュース記事",
                "ordering": ["-published", "-collected_at", "-imported_at"],
                "indexes": [
                    models.Index(
                        fields=["-published"], name="news_newsar_publish_aee1db_idx"
                    ),
                    models.Index(
                        fields=["category", "-published"],
                        name="news_newsar_categor_eeba37_idx",
                    ),
                ],
            },
        ),
    ]
